name: 'airbnb'
version: '1.0.0'
profile: 'airbnb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbnb:
    +materialized: view     # Default for models not nested
    src:
      +materialized: table  # Includes cleaned lake models (now under src)
    dim:
      +materialized: table
    fct:
      +materialized: table
